/////////////////////////////////////////////////////////////////////////////
// Name:        wxMozillaLikeAboutBoxDialog.h
// Purpose:     
// Author:      Volodymir (T-Rex) Tryapichko
// Modified by: 
// Created:     24/01/2009 17:36:37
// RCS-ID:      
// Copyright:   Copyright (c) Volodymir (T-Rex) Tryapichko, 2009
// Licence:     
/////////////////////////////////////////////////////////////////////////////

// Generated by DialogBlocks (unregistered), 24/01/2009 17:36:37

#ifndef _WXMOZILLALIKEABOUTBOXDIALOG_H_
#define _WXMOZILLALIKEABOUTBOXDIALOG_H_


/*!
 * Includes
 */

////@begin includes
#include "wx/gbsizer.h"
#include "wx/statline.h"
////@end includes

/*!
 * Forward declarations
 */

////@begin forward declarations
////@end forward declarations

/*!
 * Control identifiers
 */

////@begin control identifiers
#define SYMBOL_WXMOZILLALIKEABOUTBOXDIALOG_STYLE wxCAPTION|wxSYSTEM_MENU|wxCLOSE_BOX|wxTAB_TRAVERSAL
#define SYMBOL_WXMOZILLALIKEABOUTBOXDIALOG_TITLE _("About ")
#define SYMBOL_WXMOZILLALIKEABOUTBOXDIALOG_IDNAME ID_WXMOZILLALIKEABOUTBOXDIALOG
#define SYMBOL_WXMOZILLALIKEABOUTBOXDIALOG_SIZE wxSize(400, 300)
#define SYMBOL_WXMOZILLALIKEABOUTBOXDIALOG_POSITION wxDefaultPosition
////@end control identifiers


/*!
 * wxMozillaLikeAboutBoxDialog class declaration
 */

class wxMozillaLikeAboutBoxDialog: public wxDialog
{    
    DECLARE_DYNAMIC_CLASS( wxMozillaLikeAboutBoxDialog )
    DECLARE_EVENT_TABLE()

public:
    /// Constructors
    wxMozillaLikeAboutBoxDialog();
    wxMozillaLikeAboutBoxDialog( wxWindow* parent, 
		wxWindowID id = SYMBOL_WXMOZILLALIKEABOUTBOXDIALOG_IDNAME, 
		const wxString& caption = SYMBOL_WXMOZILLALIKEABOUTBOXDIALOG_TITLE, 
		const wxPoint& pos = SYMBOL_WXMOZILLALIKEABOUTBOXDIALOG_POSITION, 
		const wxSize& size = SYMBOL_WXMOZILLALIKEABOUTBOXDIALOG_SIZE, 
		long style = SYMBOL_WXMOZILLALIKEABOUTBOXDIALOG_STYLE );

    /// Creation
    bool Create( wxWindow* parent, 
		wxWindowID id = SYMBOL_WXMOZILLALIKEABOUTBOXDIALOG_IDNAME, 
		const wxString& caption = SYMBOL_WXMOZILLALIKEABOUTBOXDIALOG_TITLE, 
		const wxPoint& pos = SYMBOL_WXMOZILLALIKEABOUTBOXDIALOG_POSITION, 
		const wxSize& size = SYMBOL_WXMOZILLALIKEABOUTBOXDIALOG_SIZE, 
		long style = SYMBOL_WXMOZILLALIKEABOUTBOXDIALOG_STYLE );

    /// Destructor
    ~wxMozillaLikeAboutBoxDialog();

    /// Initialises member variables
    void Init();

    /// Creates the controls and sizers
    void CreateControls();

////@begin wxMozillaLikeAboutBoxDialog event handler declarations

////@end wxMozillaLikeAboutBoxDialog event handler declarations

////@begin wxMozillaLikeAboutBoxDialog member function declarations

    wxString GetAppName() const { return m_AppName ; }
    void SetAppName(wxString value) { m_AppName = value ; }

    wxString GetVersion() const { return m_Version ; }
    void SetVersion(wxString value) { m_Version = value ; }

    wxString GetCopyright() const { return m_Copyright ; }
    void SetCopyright(wxString value) { m_Copyright = value ; }

    wxString GetCustomBuildInfo() const { return m_CustomBuildInfo ; }
    void SetCustomBuildInfo(wxString value) { m_CustomBuildInfo = value ; }

    /// Retrieves bitmap resources
    wxBitmap GetBitmapResource( const wxString& name );

    /// Retrieves icon resources
    wxIcon GetIconResource( const wxString& name );
////@end wxMozillaLikeAboutBoxDialog member function declarations

    //helper functions
    enum wxBuildInfoFormat 
    {
        wxBUILDINFO_SHORT,
        wxBUILDINFO_LONG
    };

    static wxString GetBuildInfo(wxBuildInfoFormat format);
    
    void SetHeaderBitmap(const wxBitmap & value);
    void ApplyInfo();

private:
////@begin wxMozillaLikeAboutBoxDialog member variables
    wxPanel* m_ContentPanel;
    wxStaticBitmap* m_HeaderStaticBitmap;
    wxStaticText* m_AppNameStaticText;
    wxStaticText* m_CopyrightStaticText;
    wxStaticText* m_VersionStaticText;
    wxStaticText* m_BuildInfoStaticText;
    wxString m_AppName;
    wxString m_Version;
    wxString m_Copyright;
    wxString m_CustomBuildInfo;
    /// Control identifiers
    enum {
        ID_WXMOZILLALIKEABOUTBOXDIALOG = 10000,
        ID_ContentPanel = 10001
    };
////@end wxMozillaLikeAboutBoxDialog member variables
};

wxBitmap wxGetBitmapFromMemory(const void * data, size_t length);

#endif
    // _WXMOZILLALIKEABOUTBOXDIALOG_H_
